#!/bin/bash

if (( $# == 0  )) || [[ $1 == @(-h|--help) ]]; then
    echo "use: pkgbuild-watch /path/to/pkgbuilds"
    echo
    echo "path is searched for pkgbuilds"
    echo "if you have multiple paths (e.g, abs and svn)"
    echo "create a dummy directory with symlinks to each"
    echo
    echo "all pkgbuilds are searched for a _watch variable"
    echo "watch urls are added to the urlfile"
    echo "'none' to skip the check, 'package' to watch the distro page"
    echo ""
    exit
fi


pkgbuild_path=$1
urlfile=$HOME/.urlwatch/pkgbuild-watch-urls.txt
tempurl=$(mktemp)
mkdir -p "$HOME/.urlwatch"

trap 'rm -f "$tempurl"{,.2}' INT TERM EXIT

while read pkgbuild
do
    if [[ $pkgbuild == */repos/* ]]; then
        continue
    fi
    unset _watch
    source "$pkgbuild"
    if [[ $_watch == "none" ]]; then
        continue
    fi
    if [[ $_watch == "package" ]]; then
	[[ -z $pkgbase ]] && pkgbase=$pkgname
        _watch=$(expac -S "http://www.archlinux.org/packages/%r/$(uname -m)/%n/" "$pkgbase")
    fi
    if [[ -z $_watch ]]; then
        _watch=$url
    fi
    if [[ -n $_watch ]]; then
        echo "$_watch" >> "$tempurl"
    fi
done < <(find -L "$pkgbuild_path" -name 'PKGBUILD')

sort -u "$tempurl" > "$tempurl.2"
cp "$tempurl.2" "$urlfile"

urlwatch.sh "$urlfile" | less -R

